### ISSUE TITLE
Branding bar

### ISSUE THREAD

**Issue by dhannad** [ITS-UofIowa/iowalionseyebank.org#3]
Leaning toward not having a branding bar, but would like a screen shot of site with UIHC version of bar before we work to incorporate search on site.

**Comment by GaryRidgway** [comment]
They have seen this, they will get back to us on their opinion of the design

**Comment by GaryRidgway** [comment]
Customers have decided that they want a custom search on the site instead of the uiowa healthcare one

**Comment by GaryRidgway** [comment]
I have implemented a custom search bar
